### ISSUE TITLE
AttributeError: 'deviceCode2WFH' object has no attribute 'auth'

### ISSUE THREAD

**Issue by xforjustice** [kiwids0220/deviceCode2WinHello#2]
Hi,

I keep getting this error running the tool. Can you help please.

[*] requesting new PRT with Entra ID using refresh token that we request previously as client 'msbroker': 29d9ed98-a469-4536-ade2-f981bc1d605e
Traceback (most recent call last):
  File "C:\deviceCode2WinHello-main\main.py", line 269, in <module>
    main()
  File "C:\deviceCode2WinHello-main\main.py", line 257, in main
    prtdata = action.refreshtoken_to_prt_wrapper(token)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\deviceCode2WinHello-main\main.py", line 173, in refreshtoken_to_prt_wrapper
    prtdata = self.get_prt_with_refresh_token(msbroker_token["refreshToken"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\roadtools\roadlib\roadtools\roadlib\deviceauth.py", line 765, in get_prt_with_refresh_token
    return self.request_token_with_devicecert_signed_payload(payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\roadtools\roadlib\roadtools\roadlib\deviceauth.py", line 611, in request_token_with_devicecert_signed_payload
    res = self.auth.requests_post(url, data=prt_request_data, proxies=self.proxies, verify=self.verify)
          ^^^^^^^^^
AttributeError: 'deviceCode2WFH' object has no attribute 'auth'

**Comment by kiwids0220** [comment]
Hi, did you manage to fix the issue? If so, can you please share it?

**Comment by dirkjanm** [comment]
i think the issue is that both `Authentication` and `DeviceAuthentication` are expecting to have their constructors called, but this calls only one of them, which leaves the auth object empty: https://github.com/kiwids0220/deviceCode2WinHello/blob/main/main.py#L30

**Comment by kiwids0220** [comment]
> i think the issue is that both `Authentication` and `DeviceAuthentication` are expecting to have their constructors called, but this calls only one of them, which leaves the auth object empty: https://github.com/kiwids0220/deviceCode2WinHello/blob/main/main.py#L30

Thanks for identifying the underlying issue! Unfortunately I dont have a lab to test this out right now. PRs are always welcome!! If not I can try to spin up a lab over the weekend and test things out!
